### ISSUE TITLE
spec.ignore doesn't display on some clusters

### ISSUE THREAD

**Issue by sacreman** [Kubedex/helm-controller#3]
It would be good to be able to query all CRD's that are not ignored. This works on K3s.

```charts=$(kubectl get helmcharts.helm.kubedex -n helm-controller -o=jsonpath='{.items[?(@.spec.ignore==false)].metadata.name}' | tr " " "\n")```

On K3s this works and displays ignore: false when looking at the yaml output with.

```
kubectl get helmcharts.helm.kubedex.com -n helm-controller kube2iam -o yaml
```

However, on a proper Kubernetes cluster for some reason it doesn't show ignore: false under spec. But it does under annotations.

```
apiVersion: helm.kubedex.com/v1
kind: HelmChart
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"helm.kubedex.com/v1","kind":"HelmChart","metadata":{"annotations":{},"name":"kube2iam","namespace":"helm-controller"},"spec":{"chart":"kube2iam","ignore":false,"repo":"https://repo.com","targetNamespace":"kube-system","valuesContent":"node_selector: minion","version":"1.0.14"}}
```
